### ISSUE TITLE
Couple of issues during dev install

### ISSUE THREAD

**Issue by khakimov** [clemlesne/scrape-it-now#14]
- .python-version points at scrapeitnow312 which doesn't exist on the system (should it be 3.12.4?)
- `pip install pip-tools` required since using pip-sync not possible without.

**Comment by clemlesne** [comment]
The command `make install` actually does install `pip-tools`:

https://github.com/clemlesne/scrape-it-now/blob/5abe9edfe7add85be56c60f3196105a7e2c50b1d/Makefile#L29

Can you share your logs to reproduce your issue?

**Comment by clemlesne** [comment]
Closing this after 3 weeks. Don't hesitate to re open if needed.
