### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by jeremedia** [clemlesne/scrape-it-now#7]
Would be helpful those new to navigating python installs.

**Comment by clemlesne** [comment]
I'm preparing a feature to distribute standalone builds. This will make it possible to download a single file and simply run it.

Would it fit your need?

**Comment by jrbjrb1212** [comment]
@clemlesne I think @jeremedia is more looking for documentation about how to build the repo, so that the CLI interface is accessible. I too am struggling to get started with the project without documentation about setting the CLI up.

**Comment by clemlesne** [comment]
Two updates have been published:

- Installation details (https://github.com/clemlesne/scrape-it-now?tab=readme-ov-file#installation)
- Binaries are published (https://github.com/clemlesne/scrape-it-now/releases)

Does it fit your need?

**Comment by jrbjrb1212** [comment]
Yup that fit my need and I assume @jeremedia too! I can use the CLI now

**Comment by jeremedia** [comment]
Yes it does, thank you.
